networks:
  web:
    driver: bridge

volumes:
  mysql-data:
  minio-data:
  memcached-data:

services:

### PHP 7.4 ##############################################
  php-fpm-74:
    build:
      context: ./php-fpm-74
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        WORKDIR: ${WORKDIR:-/var/www}
    restart: always
    volumes:
      - ${PROJECTS_PATH}:${WORKDIR:-/var/www}
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro
      - ${HOME}/.ssh/config:/etc/ssh/ssh_config.d/hosts.conf:ro
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
    networks:
      - web

### PHP 8.3 ##############################################
  php-fpm-83:
    build:
      context: ./php-fpm-83
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        WORKDIR: ${WORKDIR:-/var/www}
    profiles: [optional]
    restart: "no"
    volumes:
      - ${PROJECTS_PATH}:${WORKDIR:-/var/www}
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro
      - ${HOME}/.ssh/config:/etc/ssh/ssh_config.d/hosts.conf:ro
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - web

### PHP 8.2 ##############################################
  php-fpm-82:
    build:
      context: ./php-fpm-82
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        WORKDIR: ${WORKDIR:-/var/www}
    restart: always
    volumes:
      - ${PROJECTS_PATH}:${WORKDIR:-/var/www}
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro
      - ${HOME}/.ssh/config:/etc/ssh/ssh_config.d/hosts.conf:ro
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - web

### PHP 8.1 ##############################################
  php-fpm-81:
    build:
      context: ./php-fpm-81
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        WORKDIR: ${WORKDIR:-/var/www}
    restart: always
    volumes:
      - ${PROJECTS_PATH}:${WORKDIR:-/var/www}
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro
      - ${HOME}/.ssh/config:/etc/ssh/ssh_config.d/hosts.conf:ro
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - web

### Nginx ################################################
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${PROJECTS_PATH}:${WORKDIR:-/var/www}
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
    depends_on:
      - php-fpm-74
    networks:
      web:
        aliases:
          - icarus.local
          - api.icarus.local
          - lms.icarus.local
          - website.icarus.local

### MySQL ################################################
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/dev.cnf:ro
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - web

### Memcached ############################################
  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "${MEMCACHED_PORT}:11211"
    networks:
      - web

### Minio ################################################
  minio:
    image: minio/minio
    restart: "no"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:${MINIO_PORT}
      MINIO_BROWSER_REDIRECT_URL: http://localhost:${MINIO_CONSOLE_PORT}
    volumes:
      - minio-data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - web

### Mailhog ##############################################
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"
    networks:
      - web

### Adminer ##############################################
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
    volumes:
      - ./adminer/index.php:/var/www/html/index.php:ro
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - web
